const fs = require('fs');
const path = require('path');

const modId = 'kubejs';
const KUBEJS_DIR = '';

// ========== JSON書き込み ==========
function writeJson(filePath, content) {
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, JSON.stringify(content, null, 2));
}

// ========== スクリプト書き込み ==========
function writeScript(filePath, content) {
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, content);
}

// ========== 1. ブロック登録用スクリプト ==========
const blocks = [
  'phuthu_log', 'phuthu_wood',
  'stripped_phuthu_log', 'stripped_phuthu_wood',
  'phuthu_planks',
  'phuthu_stairs', 'phuthu_slab',
  'phuthu_fence', 'phuthu_fence_gate'
];

const script = `
// Auto-generated by generate_kubejs_phuthum.js

StartupEvents.registry('block', event => {
  const BLOCKS = [
    '${blocks.join("', '")}'
  ];
  BLOCKS.forEach(id => event.create(id).material('wood').hardness(2.0).tagBlock('minecraft:mineable/axe'));
});

StartupEvents.registry('item', event => {
  const BLOCKS = [
    '${blocks.join("', '")}'
  ];
  BLOCKS.forEach(id => event.create(id));
});
`;

writeScript(`${KUBEJS_DIR}/startup_scripts/register_phuthu.js`, script);

// ========== 2. バイオーム JSON ==========
writeJson(`${KUBEJS_DIR}/data/${modId}/worldgen/biome/phuthum.json`, {
  precipitation: "none",
  temperature: 0.7,
  downfall: 0.0,
  effects: {
    sky_color: 11000000,
    fog_color: 6840176,
    water_color: 4159204,
    water_fog_color: 329011
  },
  features: ["#kubejs:phuthum_vegetation"],
  carvers: {},
  spawners: {},
  spawn_costs: {}
});

// ========== 3. Configured Feature ==========
writeJson(`${KUBEJS_DIR}/data/${modId}/worldgen/configured_feature/phuthu_tree.json`, {
  type: "minecraft:tree",
  config: {
    trunk_provider: {
      type: "minecraft:simple_state_provider",
      state: { Name: `${modId}:phuthu_log` }
    },
    leaves_provider: {
      type: "minecraft:simple_state_provider",
      state: { Name: `${modId}:phuthu_leaves` }
    },
    foliage_placer: {
      type: "minecraft:blob_foliage_placer",
      radius: 3,
      offset: 0,
      height: 4
    },
    trunk_placer: {
      type: "minecraft:straight_trunk_placer",
      base_height: 16,
      height_rand_a: 2,
      height_rand_b: 1
    },
    minimum_size: {
      type: "minecraft:two_layers_feature_size",
      limit: 1,
      lower_size: 1,
      upper_size: 1
    },
    ignore_vines: true
  }
});

// ========== 4. Placed Feature ==========
writeJson(`${KUBEJS_DIR}/data/${modId}/worldgen/placed_feature/phuthu_tree.json`, {
  feature: `${modId}:phuthu_tree`,
  placement: [
    { type: "minecraft:count", count: 1 },
    { type: "minecraft:in_square" },
    { type: "minecraft:heightmap", heightmap: "MOTION_BLOCKING" },
    { type: "minecraft:biome" }
  ]
});

// ========== 5. Vegetation タグ ==========
writeJson(`${KUBEJS_DIR}/data/${modId}/worldgen/tags/worldgen/placed_feature/phuthum_vegetation.json`, {
  replace: false,
  values: [`${modId}:phuthu_tree`]
});

console.log("✅ KubeJS files for Phuthum generated.");
