StartupEvents.registry('entity_type', event => {
  event.create('draizer')
    .category('monster')
    .fireImmune(true)
    .health(34)
    .armor(9)
    .dimensions(1.0, 1.5)
    .trackingRange(32)
    .clientTrackingRange(64)
    .updateInterval(1)

  event.create('scane')
    .category('monster')
    .fireImmune(false)
    .health(68)
    .armor(3)
    .dimensions(1.0, 1.5)
    .trackingRange(32)
    .clientTrackingRange(64)
    .updateInterval(1)
})
