
// Auto-generated by generate_kubejs_phuthum.js

StartupEvents.registry('block', event => {
  const BLOCKS = [
    'phuthu_log', 'phuthu_wood', 'stripped_phuthu_log', 'stripped_phuthu_wood', 'phuthu_planks', 'phuthu_stairs', 'phuthu_slab', 'phuthu_fence', 'phuthu_fence_gate'
  ];
  BLOCKS.forEach(id => event.create(id).material('wood').hardness(2.0).tagBlock('minecraft:mineable/axe'));
});

StartupEvents.registry('item', event => {
  const BLOCKS = [
    'phuthu_log', 'phuthu_wood', 'stripped_phuthu_log', 'stripped_phuthu_wood', 'phuthu_planks', 'phuthu_stairs', 'phuthu_slab', 'phuthu_fence', 'phuthu_fence_gate'
  ];
  BLOCKS.forEach(id => event.create(id));
});
