name: Generate Leafeau Textures

on:
  push:
    branches:
      - Battlity

jobs:
  generate_leafeau_textures:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install ImageMagick
        run: sudo apt-get update && sudo apt-get install -y imagemagick

      - name: Download Zephyr Texture
        run: |
          curl -O https://raw.githubusercontent.com/sakaltcommunity/Morearmors/499a7636dd3cea3e51a4827efba065e02df5919b/src/main/resources/assets/morearmors/textures/models/armor/crystal_armor_1.png
          curl -O https://raw.githubusercontent.com/sakaltcommunity/Morearmors/499a7636dd3cea3e51a4827efba065e02df5919b/src/main/resources/assets/morearmors/textures/models/armor/crystal_armor_2.png

      - name: Prepare Output Directory
        run: mkdir -p resourcepack/assets/kubejs/textures/model/armor

      - name: Generate Leafeau Textures
        run: |
          convert crystal_armor_1.png -fill "#dddd00" -colorize 75% resourcepack/assets/kubejs/textures/model/armor/provarm_armor_2.png
          convert crystal_armor_2.png -fill "#dddd00" -colorize 75% resourcepack/assets/kubejs/textures/model/armor/provarm_armor_1.png

      - name: Commit and Push Changes
        env:
          GIT_AUTHOR_NAME: GitHub Actions
          GIT_COMMITTER_NAME: GitHub Actions
          GIT_AUTHOR_EMAIL: actions@github.com
          GIT_COMMITTER_EMAIL: actions@github.com
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.SECRET_TOKEN }}@github.com/${{ github.repository }}

          git add resourcepack/assets/kubejs/textures/model/armor/provarm_armor_1.png \
                  resourcepack/assets/kubejs/textures/model/armor/provarm_armor_2.png
          git commit -m "Generate Leafeau textures from crystal base" || echo "No changes to commit"
          git pull --rebase origin Battlity || echo "Pull failed (likely due to conflicts or clean state)"
          git push origin HEAD:Battlity
