name: Upload Moreweapons artifact to CurseForge

on:
  workflow_dispatch:

jobs:
  upload_artifact:
    runs-on: ubuntu-latest

    steps:
      - name: Get artifact download URL
        id: get_url
        run: |
          echo "Getting artifact archive URL..."
          url=$(curl -s -H "Authorization: token ${{ secrets.GH_PAT }}" \
              https://api.github.com/repos/Konnitiwa768/Moreweapons/actions/artifacts/3245302374/zip \
              -D - | grep -i Location | awk '{print $2}' | tr -d '\r')
          echo "artifact_url=$url" >> $GITHUB_OUTPUT

      - name: Download artifact zip
        run: |
          curl -L "${{ steps.get_url.outputs.artifact_url }}" -o artifact.zip

      - name: Unzip artifact
        run: |
          mkdir artifact
          unzip artifact.zip -d artifact
          ls -R artifact

      - name: Upload to CurseForge
        run: |
          curl -X POST "https://minecraft.curseforge.com/api/v1/mods/${{ secrets.PROJECT_ID }}/files" \
            -H "x-api-key: ${{ secrets.CURSEFORGE_API_KEY }}" \
            -F "metadata={
              \"gameVersions\": [\"${{ secrets.GAME_VERSION }}\"],
              \"releaseType\": \"release\",
              \"displayName\": \"Built.jar from Moreweapons\"
            };type=application/json" \
            -F "file=@artifact/Built.jar;type=application/java-archive"
