name: Upload to CurseForge

on:
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Create artifact directory
        run: mkdir -p artifact

      - name: Download Built.jar from artifact
        run: |
          curl -L -o artifact/Built.jar \
            -H "Accept: application/octet-stream" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://github.com/Konnitiwa768/Moreweapons/actions/runs/15403945338/artifacts/3245302374"

      - name: Upload to CurseForge
        run: |
          curl -X POST https://minecraft.curseforge.com/api/v1/mods/${{ secrets.PROJECT_ID }}/files \
          -H "x-api-key: ${{ secrets.CURSEFORGE_API_KEY }}" \
          -F "metadata={
              \"gameVersions\": [\"${{ secrets.GAME_VERSION }}\"],
              \"releaseType\": \"release\",
              \"displayName\": \"Built.jar automated upload\",
              \"relations\": {}
            };type=application/json" \
          -F "file=@artifacts/built.jar;type=application/java-archive"
