name: Upload to CurseForge

on:
  workflow_dispatch:

jobs:
  download_and_upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: Built
          path: artifact

      - name: Display artifact contents
        run: ls -R artifact

      - name: Upload to CurseForge
        run: |
          curl -X POST "https://minecraft.curseforge.com/api/v1/mods/${{ secrets.PROJECT_ID }}/files" \
            -H "x-api-key: ${{ secrets.CURSEFORGE_API_KEY }}" \
            -F "metadata={
              \"gameVersions\": [\"${{ secrets.GAME_VERSION }}\"],
              \"releaseType\": \"release\",
              \"displayName\": \"Built.jar automated upload\"
            };type=application/json" \
            -F "file=@artifact/Built.jar;type=application/java-archive"
