name: Generate Leafeau Textures

on:
  push:
    branches:
      - refs/heads/Battlity

jobs:
  generate_leafeau_textures:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install -y imagemagick file

      - name: Prepare Oak Files List
        run: |
          # Oakを含むファイル名だけをリスト
          echo "leaves_oak.png" > oak_files.txt
          echo "log_oak.png" >> oak_files.txt
          echo "planks_oak.png" >> oak_files.txt
          # 必要なOakファイル名をここに追加

      - name: Download PNG Images and Remove Broken Ones
        run: |
          while read file; do
            curl -f -O "https://raw.githubusercontent.com/Mojang/bedrock-samples/main/resource_pack/textures/block/$file"
            if ! file "$file" | grep -q 'PNG image data'; then
              echo "$file はPNG画像ではありません。削除します。"
              rm -f "$file"
            fi
          done < oak_files.txt

      - name: Generate Leafeau Textures
        run: |
          mkdir -p resourcepack/assets/kubejs/textures/block
          for file in *.png; do
            [ -e "$file" ] || continue
            base=$(basename "$file" .png)
            convert "$file" -fill "#753dcf" -colorize 50% "resourcepack/assets/kubejs/textures/block/phuthu_${base}.png"
          done

      - name: Commit and Push Changes
        env:
          GIT_AUTHOR_NAME: GitHub Actions
          GIT_COMMITTER_NAME: GitHub Actions
          GIT_AUTHOR_EMAIL: actions@github.com
          GIT_COMMITTER_EMAIL: actions@github.com
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.SECRET_TOKEN }}@github.com/${{ github.repository }}

          git add resourcepack/assets/kubejs/textures/block/phuthu_*.png
          git commit -m "Generate Leafeau textures from oak base" || echo "No changes to commit"
          git pull --rebase origin Battlity || echo "Pull failed (likely due to conflicts or clean state)"
          git push origin HEAD:Battlity
