name: Generate Leafeau Textures

on:
  push:
    branches:
      - Battlity

jobs:
  generate_leafeau_textures:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install -y imagemagick jq

      - name: Download All Oak Textures
        run: |
          # APIからitemsディレクトリのファイル一覧取得
          response=$(curl -s https://api.github.com/repos/Mojang/bedrock-samples/contents/resource_pack/textures/block)
          # JSONが配列ならoakファイルを抽出、そうでなければエラー出力
          if echo "$response" | jq 'type' | grep -q '"array"'; then
            echo "$response" | jq -r '.[] | select(.name | test("oak")) | .name' > oak_files.txt
          else
            echo "$response" | jq -r '.message // .'
            exit 1
          fi

          # 対象ファイルが存在するか確認
          if [ ! -s oak_files.txt ]; then
            echo "No oak files found."
            exit 0
          fi

          # oakを含むファイルをすべてダウンロード
          while read file; do
            curl -O https://raw.githubusercontent.com/Mojang/bedrock-samples/main/resource_pack/textures/block/$file
          done < oak_files.txt

      - name: Generate Leafeau Textures
        run: |
          mkdir -p resourcepack/assets/kubejs/textures/block
          while read file; do
            base=$(basename $file .png)
            convert $file -fill "#753dcf" -colorize 50% resourcepack/assets/kubejs/textures/block/phuthu_${base}.png
          done < oak_files.txt

      - name: Commit and Push Changes
        env:
          GIT_AUTHOR_NAME: GitHub Actions
          GIT_COMMITTER_NAME: GitHub Actions
          GIT_AUTHOR_EMAIL: actions@github.com
          GIT_COMMITTER_EMAIL: actions@github.com
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.SECRET_TOKEN }}@github.com/${{ github.repository }}

          # 生成されたファイルをgit add
          git add resourcepack/assets/kubejs/textures/block/phuthu_*.png
          git commit -m "Generate Leafeau textures from oak base" || echo "No changes to commit"
          git pull --rebase origin Battlity || echo "Pull failed (likely due to conflicts or clean state)"
          git push origin HEAD:Battlity
