name: Nether Star Armor Texture Clip & Convert

on:
  push:
    branches:
      - Battlity
  pull_request:
    branches:
      - Battlity
  workflow_dispatch:

jobs:
  armor_texture_process:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install ImageMagick
        run: sudo apt-get update && sudo apt-get install -y imagemagick

      # 先頭大文字PNGを全削除
      # - name: //assets/kubejs/textures/item -type f -iname '[A-Z]*.png' -delete || true

      - name: Download original images
        run: |
          for item in helmet chestplate leggings boots; do
            curl -L -o "nether_star_${item}.png" "https://raw.githubusercontent.com/Konnitiwa768/Morearmors/main/src/main/resources/assets/morearmors/textures/items/nether_star_${item}.png"
          done

      # 1. そのまま色変更なしでくり抜き（clip）
      - name: Clip images (original color, no recolor)
        run: |
          mkdir -p resourcepack/assets/kubejs/textures/item
          for item in helmet chestplate leggings boots; do
            convert "nether_star_${item}.png" -resize 16x16^ -gravity center -extent 16x16 \
              -alpha on "resourcepack/assets/kubejs/textures/item/nether_star_${item}.png"
          done

      # 2. 色変換＋透明維持（convert）
      - name: Convert images with ImageMagick (clipping + color)
        run: |
          set -e

          # recolor: 透明部分維持して色だけ置換（クリッピング）
          recolor() {
            src=$1
            color=$2
            prefix=$3
            part=$4
            out="resourcepack/assets/kubejs/textures/item/${prefix}_${part}.png"
            convert "$src" -resize 16x16^ -gravity center -extent 16x16 \
              -alpha on -channel RGB -fill "$color" -colorize 60% "$out"
          }

          # spectrium: 上半分緑・下半分黄で透明部分維持
          spectrium() {
            src=$1
            prefix=$2
            part=$3
            out="resourcepack/assets/kubejs/textures/item/${prefix}_${part}.png"
            convert "$src" -resize 16x16^ -gravity center -extent 16x16 -alpha extract mask.png
            convert -size 16x8 xc:'#44ff44' upper.png
            convert -size 16x8 xc:'#cccc00' lower.png
            convert upper.png lower.png -append color.png
            convert color.png mask.png -compose CopyOpacity -composite colorclip.png
            convert "$src" -resize 16x16^ -gravity center -extent 16x16 \
              \( colorclip.png \) -compose SrcIn -composite "$out"
            rm upper.png lower.png color.png mask.png colorclip.png
          }

          # prefixはすべて小文字
          declare -A PREFIXES=(
            [demlight]="demlight"
            [provarm]="provarm"
            [spectrium]="spectrium"
          )

          for item in helmet chestplate leggings boots; do
            recolor "nether_star_${item}.png" "#753dcf" "${PREFIXES[demlight]}" "$item"
            recolor "nether_star_${item}.png" "#dd0000" "${PREFIXES[provarm]}" "$item"
            spectrium "nether_star_${item}.png" "${PREFIXES[spectrium]}" "$item"
          done

      - name: Commit all images
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add resourcepack/assets/kubejs/textures/item
          git commit -m "auto: clip original & color armor textures (lowercase, capitalized removed)" || echo "No changes to commit"
          git push
