name: Nether Star Armor Texture Clip & Convert

on:
  push:
    branches:
      - Battlity
  pull_request:
    branches:
      - Battlity
  workflow_dispatch:

jobs:
  armor_texture_process:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install ImageMagick
        run: sudo apt-get update && sudo apt-get install -y imagemagick

      # オリジナル画像DL
      - name: Download original images
        run: |
          for item in helmet chestplate leggings boots; do
            curl -L -o "nether_star_${item}.png" "https://raw.githubusercontent.com/Konnitiwa768/Morearmors/main/src/main/resources/assets/morearmors/textures/items/nether_star_${item}.png"
          done

      # Nether Star clip（元画像の不透明部分だけをくり抜く）
      - name: Clip original images (opaque only)
        run: |
          mkdir -p resourcepack/assets/kubejs/textures/item
          for item in helmet chestplate leggings boots; do
            convert "nether_star_${item}.png" -alpha extract mask.png
            convert "nether_star_${item}.png" mask.png -alpha off -compose CopyOpacity -composite \
              "resourcepack/assets/kubejs/textures/item/nether_star_${item}_opaqueclip.png"
            rm mask.png
          done

      # recolor, spectrium画像の生成とclip
      - name: Convert and clip recolor/spectrium images (hue shift)
        run: |
          set -e
          mkdir -p resourcepack/assets/kubejs/textures/item

          # recolor: 色相シフトで色変更
          recolor() {
            src=$1
            hue_shift=$2
            prefix=$3
            part=$4
            out="resourcepack/assets/kubejs/textures/item/${prefix}_${part}.png"
            convert "$src" -resize 16x16^ -gravity center -extent 16x16 \
              -alpha on -modulate 100,100,"$hue_shift" "$out"
          }

          # spectrium: 上半分と下半分で色相シフト値を変える
          spectrium() {
            src=$1
            prefix=$2
            part=$3
            out="resourcepack/assets/kubejs/textures/item/${prefix}_${part}.png"
            upper_hue=80    # 上半分: 緑系
            lower_hue=20   # 下半分: 黄系

            convert "$src" -resize 16x16^ -gravity center -extent 16x16 tmp_full.png
            convert tmp_full.png -crop 16x8+0+0 +repage upper.png
            convert tmp_full.png -crop 16x8+0+8 +repage lower.png

            convert upper.png -alpha on -modulate 100,100,"$upper_hue" upper_hue.png
            convert lower.png -alpha on -modulate 100,100,"$lower_hue" lower_hue.png

            convert upper_hue.png lower_hue.png -append tmp_spectrium.png
            convert tmp_full.png -alpha extract mask.png
            convert tmp_spectrium.png mask.png -compose CopyOpacity -composite "$out"

            rm upper.png lower.png upper_hue.png lower_hue.png tmp_spectrium.png tmp_full.png mask.png
          }

          # くり抜きclip関数
          clip_opaque() {
            input_img=$1
            output_img=$2
            convert "$input_img" -alpha extract mask.png
            convert "$input_img" mask.png -alpha off -compose CopyOpacity -composite "$output_img"
            rm mask.png
          }

          declare -A PREFIXES=(
            [demlight]="demlight"
            [provarm]="provarm"
            [spectrium]="spectrium"
          )

          for item in helmet chestplate leggings boots; do
            # recolor
            recolor "nether_star_${item}.png" 138 "${PREFIXES[demlight]}" "$item"   # demlight: 138
            recolor "nether_star_${item}.png" 10 "${PREFIXES[provarm]}" "$item"     # provarm: 10
            # spectrium（上下でhueを変える）
            spectrium "nether_star_${item}.png" "${PREFIXES[spectrium]}" "$item"

            # 各リカラー・スペクトリウム画像もclip（不透明部分だけくり抜き）
            for prefix in demlight provarm spectrium; do
              src="resourcepack/assets/kubejs/textures/item/${prefix}_${item}.png"
              out="resourcepack/assets/kubejs/textures/item/${prefix}_${item}_opaqueclip.png"
              clip_opaque "$src" "$out"
            done
          done

      # 自動コミット＆push前にpull --rebase
      - name: Commit and push all images safely
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add resourcepack/assets/kubejs/textures/item
          git commit -m "auto: clip & convert armor textures (hue-shift, spectrium split hue)" || echo "No changes to commit"
          git pull --rebase origin Battlity
          git push origin HEAD:Battlity
