name: Nether Star Armor Texture Convert

on:
  push:
    branches:
      - Battlity
  pull_request:
    branches:
      - Battlity
  workflow_dispatch:

jobs:
  convert_textures:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install ImageMagick
        run: sudo apt-get update && sudo apt-get install -y imagemagick

      - name: Prepare directories
        run: mkdir -p resourcepack/assets/kubejs/textures/item

      - name: Delete old converted files
        run: |
          rm -f resourcepack/assets/kubejs/textures/item/demlight_*.png || true
          rm -f resourcepack/assets/kubejs/textures/item/provarm_*.png || true
          rm -f resourcepack/assets/kubejs/textures/item/spectrium_*.png || true
          rm -f resourcepack/assets/kubejs/textures/item/provurm_*.png || true

      - name: Download original images
        run: |
          for item in helmet chestplate leggings boots; do
            curl -L -o "nether_star_${item}.png" "https://raw.githubusercontent.com/Konnitiwa768/Morearmors/main/src/main/resources/assets/morearmors/textures/items/nether_star_${item}.png"
          done

      - name: Convert images with ImageMagick (クリップ式で透明化＆小文字)
        run: |
          set -e

          # recolor: クリップ式透明処理＋小文字ファイル名
          recolor() {
            src=$1
            color=$2
            prefix=$3
            part=$4
            out="resourcepack/assets/kubejs/textures/item/${prefix}_${part}.png"
            convert "$src" -resize 16x16^ -gravity center -extent 16x16 -alpha extract mask.png
            convert -size 16x16 xc:"rgba($color,1.0)" mask.png -compose CopyOpacity -composite "$out"
            rm mask.png
          }

          # spectrium: 上半分44ff44(緑), 下半分cccc00(黄)をクリップ
          spectrium() {
            src=$1
            prefix=$2
            part=$3
            out="resourcepack/assets/kubejs/textures/item/${prefix}_${part}.png"
            convert "$src" -resize 16x16^ -gravity center -extent 16x16 -alpha extract msk.png
            convert -size 16x8 xc:'rgba(68,255,68,1.0)' upper.png
            convert -size 16x8 xc:'rgba(204,204,0,1.0)' lower.png
            convert upper.png lower.png -append color.png
            convert color.png msk.png -compose CopyOpacity -composite "$out"
            rm upper.png lower.png color.png msk.png
          }

          # 小文字prefix
          declare -A PREFIXES=(
            [demlight]="demlight"
            [provarm]="provarm"
            [spectrium]="spectrium"
          )

          for item in helmet chestplate leggings boots; do
            recolor "nether_star_${item}.png" "117,61,207" "${PREFIXES[demlight]}" "$item"
            recolor "nether_star_${item}.png" "221,221,0" "${PREFIXES[provarm]}" "$item"
            spectrium "nether_star_${item}.png" "${PREFIXES[spectrium]}" "$item"
          done

      - name: Commit converted images
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add resourcepack/assets/kubejs/textures/item
          git commit -m "Auto: regenerate armor textures with lowercase and proper mask clip" || echo "No changes to commit"
          git push
