name: Generate Leafeau Textures (curl -o & python, files as array, oak_*.png)

on:
  push:
    branches:
      - Battlity

jobs:
  generate_leafeau_textures:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git curl python3 python3-pip
          pip3 install pillow

      - name: Download and Convert Oak Textures (skip oak_log & oak_leaves)
        run: |
          mkdir -p resourcepack/assets/kubejs/textures/block
          files=(
            oak_planks.png
            oak_stripped_log.png
            oak_stripped_wood.png
            oak_wood.png
            oak_door.png
            oak_trapdoor.png
            oak_pressure_plate.png
            oak_button.png
            oak_fence.png
            oak_fence_gate.png
            oak_stairs.png
            oak_slab.png
            oak_sign.png
            oak_boat.png
            oak_hanging_sign.png
            oak_chest.png
            oak_bookshelf.png
            oak_sapling.png
          )
          for file in "${files[@]}"; do
            if [ -f "resourcepack/assets/kubejs/textures/block/phuthu_$file" ]; then
              echo "Skip $file (already exists)"
              continue
            fi
            echo "Downloading $file"
            curl -f -o "$file" "https://raw.githubusercontent.com/Mojang/bedrock-samples/refs/heads/main/resource_pack/textures/block/$file"
            python3 convert_oak_to_phuthu.py "$file" "resourcepack/assets/kubejs/textures/block/phuthu_$file"
            rm -f "$file"
          done

      - name: Commit and Push Changes
        env:
          GIT_AUTHOR_NAME: GitHub Actions
          GIT_COMMITTER_NAME: GitHub Actions
          GIT_AUTHOR_EMAIL: actions@github.com
          GIT_COMMITTER_EMAIL: actions@github.com
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.SECRET_TOKEN }}@github.com/${{ github.repository }}
          git add resourcepack/assets/kubejs/textures/block/phuthu_*.png
          git commit -m "Generate Leafeau textures from oak base (curl -o & python, files as array, oak_*.png)" || echo "No changes to commit"
          git pull --rebase origin Battlity || echo "Pull failed"
          git push origin HEAD:Battlity
